#thanos-values.yaml
#use the identityProfile": {
  #  "kubeletidentity": {
   #   "clientId" as user_assigned_id
objstoreConfig: |-
  type: AZURE
  config:
    storage_account: "thanostore"
    container: "thanostore"
    endpoint: "blob.core.windows.net"
    max_retries: 0
    user_assigned_id: "5c424851-e907-4cb0-acb5-3ea42fc56082"

ruler:
  enabled: true
  
query:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: "1"
    maxReplicas: "10"
    targetCPU: "60"
    targetMemory: "60"
  stores:
    - thanos-storegateway.thanos.svc.cluster.local:10901

queryFrontend:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: "1"
    maxReplicas: "10"
    targetCPU: "60"
    targetMemory: "60"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - thanos'
    hostname: query.thanos.cookingwithazure.com
    ingressClassName: nginx
    tls: true

bucketweb:
  enabled: true
  refresh: "10m"

compactor:
  enabled: true
  ## Resolution and Retention flags
  ## @param compactor.retentionResolutionRaw Resolution and Retention flag
  ## @param compactor.retentionResolution5m Resolution and Retention flag
  ## @param compactor.retentionResolution1h Resolution and Retention flag
  ##
  retentionResolutionRaw: 180d
  retentionResolution5m: 2y
  retentionResolution1h: 5y

  ## Persistence parameters
  ##
  persistence:
    ## @param compactor.persistence.enabled Enable data persistence using PVC(s) on Thanos Compactor pods
    ##
    enabled: false

storegateway:
  enabled: true


ruler:
  enabled: false

receive:
  enabled: true
  persistence:
    enabled: true
  tsdbRetention: 90d
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - thanos'
    hostname: receive.thanos.cookingwithazure.com
    ingressClassName: nginx
    tls: true

# metrics:
#   enabled: true
#   serviceMonitor:
#     enabled: true
#     labels:
#       release: prom