rbac:
  pspEnabled: false
persistence:
  type: pvc
  enabled: true
grafana.ini:
    server:
      root_url: 'https://grafana.thanos.cookingwithazure.com'
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Thanos
      type: prometheus
      url: http://thanos-query-frontend.thanos:9090
      access: proxy
      isDefault: true
plugins:
  - grafana-worldmap-panel
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Thanos
    kube-global-view:
      gnetId: 15757
      revision: 14
      datasource: Thanos
ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  ingressClassName: nginx
  path: /
  pathType: ImplementationSpecific
  hosts:
    - grafana.thanos.cookingwithazure.com
  tls:
  - secretName: grafana-tls
    hosts:
      - grafana.thanos.cookingwithazure.com
